### ISSUE TITLE
hey man，where is releases the jrpc 3.1 jar？

### ISSUE THREAD

**Issue by sundayha** [dinstone/jrpc#2]

**Comment by dinstone** [comment]
We are preparing for the release of 3.1.0. You can find it in the central repository later.

**Comment by dinstone** [comment]
We are preparing for the release of 3.1.0. You can find it in the central repository later.

**Comment by dinstone** [comment]
JRPC 3.1.0 released, you can find it in the central repository now.

**Comment by sundayha** [comment]
@dinstone ok i got it thanks
