### ISSUE TITLE
How can I use it with javascript client?

### ISSUE THREAD

**Issue by buckelieg** [dinstone/jrpc#3]
I want to use this library as a server side service that accessed vie RPC.
On the client side I have a web page and going to use JRPC over HTTP.
Is this possible?
Thank  you.

**Comment by dinstone** [comment]
the javascript client of the web page can't access JRPC service over http, because JRPC is over TCP and the RPC protocol is customed. if you want，the socketio based on vert.x framework is  a good idea.
